// Code generated by mockery. DO NOT EDIT.

package poster_mocks

import (
	image "image"

	gg "github.com/fogleman/gg"

	mock "github.com/stretchr/testify/mock"
)

// ImageProcessor is an autogenerated mock type for the ImageProcessor type
type ImageProcessor struct {
	mock.Mock
}

type ImageProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *ImageProcessor) EXPECT() *ImageProcessor_Expecter {
	return &ImageProcessor_Expecter{mock: &_m.Mock}
}

// CreateContext provides a mock function with given fields: width, height
func (_m *ImageProcessor) CreateContext(width int, height int) *gg.Context {
	ret := _m.Called(width, height)

	if len(ret) == 0 {
		panic("no return value specified for CreateContext")
	}

	var r0 *gg.Context
	if rf, ok := ret.Get(0).(func(int, int) *gg.Context); ok {
		r0 = rf(width, height)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gg.Context)
		}
	}

	return r0
}

// ImageProcessor_CreateContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateContext'
type ImageProcessor_CreateContext_Call struct {
	*mock.Call
}

// CreateContext is a helper method to define mock.On call
//   - width int
//   - height int
func (_e *ImageProcessor_Expecter) CreateContext(width interface{}, height interface{}) *ImageProcessor_CreateContext_Call {
	return &ImageProcessor_CreateContext_Call{Call: _e.mock.On("CreateContext", width, height)}
}

func (_c *ImageProcessor_CreateContext_Call) Run(run func(width int, height int)) *ImageProcessor_CreateContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *ImageProcessor_CreateContext_Call) Return(_a0 *gg.Context) *ImageProcessor_CreateContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ImageProcessor_CreateContext_Call) RunAndReturn(run func(int, int) *gg.Context) *ImageProcessor_CreateContext_Call {
	_c.Call.Return(run)
	return _c
}

// OpenImage provides a mock function with given fields: filePath
func (_m *ImageProcessor) OpenImage(filePath string) (image.Image, error) {
	ret := _m.Called(filePath)

	if len(ret) == 0 {
		panic("no return value specified for OpenImage")
	}

	var r0 image.Image
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (image.Image, error)); ok {
		return rf(filePath)
	}
	if rf, ok := ret.Get(0).(func(string) image.Image); ok {
		r0 = rf(filePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(image.Image)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(filePath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ImageProcessor_OpenImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenImage'
type ImageProcessor_OpenImage_Call struct {
	*mock.Call
}

// OpenImage is a helper method to define mock.On call
//   - filePath string
func (_e *ImageProcessor_Expecter) OpenImage(filePath interface{}) *ImageProcessor_OpenImage_Call {
	return &ImageProcessor_OpenImage_Call{Call: _e.mock.On("OpenImage", filePath)}
}

func (_c *ImageProcessor_OpenImage_Call) Run(run func(filePath string)) *ImageProcessor_OpenImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ImageProcessor_OpenImage_Call) Return(_a0 image.Image, _a1 error) *ImageProcessor_OpenImage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ImageProcessor_OpenImage_Call) RunAndReturn(run func(string) (image.Image, error)) *ImageProcessor_OpenImage_Call {
	_c.Call.Return(run)
	return _c
}

// ResizeImage provides a mock function with given fields: img, width, height
func (_m *ImageProcessor) ResizeImage(img image.Image, width int, height int) image.Image {
	ret := _m.Called(img, width, height)

	if len(ret) == 0 {
		panic("no return value specified for ResizeImage")
	}

	var r0 image.Image
	if rf, ok := ret.Get(0).(func(image.Image, int, int) image.Image); ok {
		r0 = rf(img, width, height)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(image.Image)
		}
	}

	return r0
}

// ImageProcessor_ResizeImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResizeImage'
type ImageProcessor_ResizeImage_Call struct {
	*mock.Call
}

// ResizeImage is a helper method to define mock.On call
//   - img image.Image
//   - width int
//   - height int
func (_e *ImageProcessor_Expecter) ResizeImage(img interface{}, width interface{}, height interface{}) *ImageProcessor_ResizeImage_Call {
	return &ImageProcessor_ResizeImage_Call{Call: _e.mock.On("ResizeImage", img, width, height)}
}

func (_c *ImageProcessor_ResizeImage_Call) Run(run func(img image.Image, width int, height int)) *ImageProcessor_ResizeImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(image.Image), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *ImageProcessor_ResizeImage_Call) Return(_a0 image.Image) *ImageProcessor_ResizeImage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ImageProcessor_ResizeImage_Call) RunAndReturn(run func(image.Image, int, int) image.Image) *ImageProcessor_ResizeImage_Call {
	_c.Call.Return(run)
	return _c
}

// SaveImage provides a mock function with given fields: img, filePath
func (_m *ImageProcessor) SaveImage(img image.Image, filePath string) (string, error) {
	ret := _m.Called(img, filePath)

	if len(ret) == 0 {
		panic("no return value specified for SaveImage")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(image.Image, string) (string, error)); ok {
		return rf(img, filePath)
	}
	if rf, ok := ret.Get(0).(func(image.Image, string) string); ok {
		r0 = rf(img, filePath)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(image.Image, string) error); ok {
		r1 = rf(img, filePath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ImageProcessor_SaveImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveImage'
type ImageProcessor_SaveImage_Call struct {
	*mock.Call
}

// SaveImage is a helper method to define mock.On call
//   - img image.Image
//   - filePath string
func (_e *ImageProcessor_Expecter) SaveImage(img interface{}, filePath interface{}) *ImageProcessor_SaveImage_Call {
	return &ImageProcessor_SaveImage_Call{Call: _e.mock.On("SaveImage", img, filePath)}
}

func (_c *ImageProcessor_SaveImage_Call) Run(run func(img image.Image, filePath string)) *ImageProcessor_SaveImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(image.Image), args[1].(string))
	})
	return _c
}

func (_c *ImageProcessor_SaveImage_Call) Return(_a0 string, _a1 error) *ImageProcessor_SaveImage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ImageProcessor_SaveImage_Call) RunAndReturn(run func(image.Image, string) (string, error)) *ImageProcessor_SaveImage_Call {
	_c.Call.Return(run)
	return _c
}

// NewImageProcessor creates a new instance of ImageProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewImageProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *ImageProcessor {
	mock := &ImageProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
