// Code generated by mockery. DO NOT EDIT.

package media_mocks

import mock "github.com/stretchr/testify/mock"

// MediaResponse is an autogenerated mock type for the MediaResponse type
type MediaResponse struct {
	mock.Mock
}

type MediaResponse_Expecter struct {
	mock *mock.Mock
}

func (_m *MediaResponse) EXPECT() *MediaResponse_Expecter {
	return &MediaResponse_Expecter{mock: &_m.Mock}
}

// NewMediaResponse creates a new instance of MediaResponse. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMediaResponse(t interface {
	mock.TestingT
	Cleanup(func())
}) *MediaResponse {
	mock := &MediaResponse{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
