// Code generated by mockery. DO NOT EDIT.

package rating_mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
	rating "github.com/zepollabot/media-rating-overlay/internal/rating-service"

	url "net/url"
)

// RatingClient is an autogenerated mock type for the RatingClient type
type RatingClient struct {
	mock.Mock
}

type RatingClient_Expecter struct {
	mock *mock.Mock
}

func (_m *RatingClient) EXPECT() *RatingClient_Expecter {
	return &RatingClient_Expecter{mock: &_m.Mock}
}

// DoWithRatingResponse provides a mock function with given fields: request
func (_m *RatingClient) DoWithRatingResponse(request *http.Request) (rating.RatingResponse, error) {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for DoWithRatingResponse")
	}

	var r0 rating.RatingResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*http.Request) (rating.RatingResponse, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(*http.Request) rating.RatingResponse); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rating.RatingResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RatingClient_DoWithRatingResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoWithRatingResponse'
type RatingClient_DoWithRatingResponse_Call struct {
	*mock.Call
}

// DoWithRatingResponse is a helper method to define mock.On call
//   - request *http.Request
func (_e *RatingClient_Expecter) DoWithRatingResponse(request interface{}) *RatingClient_DoWithRatingResponse_Call {
	return &RatingClient_DoWithRatingResponse_Call{Call: _e.mock.On("DoWithRatingResponse", request)}
}

func (_c *RatingClient_DoWithRatingResponse_Call) Run(run func(request *http.Request)) *RatingClient_DoWithRatingResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*http.Request))
	})
	return _c
}

func (_c *RatingClient_DoWithRatingResponse_Call) Return(_a0 rating.RatingResponse, _a1 error) *RatingClient_DoWithRatingResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RatingClient_DoWithRatingResponse_Call) RunAndReturn(run func(*http.Request) (rating.RatingResponse, error)) *RatingClient_DoWithRatingResponse_Call {
	_c.Call.Return(run)
	return _c
}

// DoWithResponse provides a mock function with given fields: request
func (_m *RatingClient) DoWithResponse(request *http.Request) (*http.Response, error) {
	ret := _m.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for DoWithResponse")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(*http.Request) (*http.Response, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(*http.Request) *http.Response); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RatingClient_DoWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoWithResponse'
type RatingClient_DoWithResponse_Call struct {
	*mock.Call
}

// DoWithResponse is a helper method to define mock.On call
//   - request *http.Request
func (_e *RatingClient_Expecter) DoWithResponse(request interface{}) *RatingClient_DoWithResponse_Call {
	return &RatingClient_DoWithResponse_Call{Call: _e.mock.On("DoWithResponse", request)}
}

func (_c *RatingClient_DoWithResponse_Call) Run(run func(request *http.Request)) *RatingClient_DoWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*http.Request))
	})
	return _c
}

func (_c *RatingClient_DoWithResponse_Call) Return(_a0 *http.Response, _a1 error) *RatingClient_DoWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RatingClient_DoWithResponse_Call) RunAndReturn(run func(*http.Request) (*http.Response, error)) *RatingClient_DoWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetBaseUrl provides a mock function with no fields
func (_m *RatingClient) GetBaseUrl() *url.URL {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBaseUrl")
	}

	var r0 *url.URL
	if rf, ok := ret.Get(0).(func() *url.URL); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*url.URL)
		}
	}

	return r0
}

// RatingClient_GetBaseUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBaseUrl'
type RatingClient_GetBaseUrl_Call struct {
	*mock.Call
}

// GetBaseUrl is a helper method to define mock.On call
func (_e *RatingClient_Expecter) GetBaseUrl() *RatingClient_GetBaseUrl_Call {
	return &RatingClient_GetBaseUrl_Call{Call: _e.mock.On("GetBaseUrl")}
}

func (_c *RatingClient_GetBaseUrl_Call) Run(run func()) *RatingClient_GetBaseUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RatingClient_GetBaseUrl_Call) Return(_a0 *url.URL) *RatingClient_GetBaseUrl_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RatingClient_GetBaseUrl_Call) RunAndReturn(run func() *url.URL) *RatingClient_GetBaseUrl_Call {
	_c.Call.Return(run)
	return _c
}

// NewRatingClient creates a new instance of RatingClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRatingClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *RatingClient {
	mock := &RatingClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
