// Code generated by mockery. DO NOT EDIT.

package rating_mocks

import mock "github.com/stretchr/testify/mock"

// RatingResponse is an autogenerated mock type for the RatingResponse type
type RatingResponse struct {
	mock.Mock
}

type RatingResponse_Expecter struct {
	mock *mock.Mock
}

func (_m *RatingResponse) EXPECT() *RatingResponse_Expecter {
	return &RatingResponse_Expecter{mock: &_m.Mock}
}

// NewRatingResponse creates a new instance of RatingResponse. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRatingResponse(t interface {
	mock.TestingT
	Cleanup(func())
}) *RatingResponse {
	mock := &RatingResponse{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
