# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Tidy modules
      run: go mod tidy

    - name: Download dependencies
      run: go mod download

    - name: Build
      run: go build -v ./...

    - name: Run Test
      run: |
        go list ./... | grep -v -E '(/vendor/|/mocks)' | xargs go test -v -coverprofile=coverage.txt


    - name: Upload results to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: zepollabot/media-rating-overlay
